#!/usr/bin/env bash

current_dir=$(
    cd $(dirname $BASH_SOURCE)
    pwd
)

source "${current_dir}/local/share/shell/argsparse.sh"

usage() {
    printf "Bootstrap script, supported choices:\n"
    printf "\tterminal: install terminal tools\n"
    printf "\tenv: pyenv+asdf\n"
    printf "\ttexlive: texlive\n"
    printf "\tdevelop: above+develop tools\n"
    printf "\tfull: above+desktop environments\n"
    printf "Beginning of usage:\n"
    argsparse_usage
    printf "End of useage\n"
    exit 16
}

argsparse_use_option choose "choose install specified environments" value mandatory
option_choose_values=(terminal env texlive develop full)

argsparse_parse_options "$@"

args_only=${program_options[choose]}

yay_packages=()
apt_packages=()
additional_commands=()

download() {
    filename=$1
    url=$2
    mkdir -p $(dirname $filename)

    if [ ! -f $1 ]; then
        echo "download $url to $filename"
        curl $url -o $filename
    else
        echo "$filename exists, skip"
    fi
}

setup_pyenv() {
    yay_packages+=(
        openssl
        zlib
        xz
        tk
    )
    apt_packages+=(
        build-essential
        libssl-dev
        zlib1g-dev
        libbz2-dev
        libreadline-dev
        libsqlite3-dev
        curl
        libncursesw5-dev
        xz-utils
        tk-dev
        libxml2-dev
        libxmlsec1-dev
        libffi-dev
        liblzma-dev
    )

    if [ ! -d ~/.pyenv ]; then
        echo "installing pyenv..."
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    else
        echo "pyenv installed, skip"
    fi

    pyenv_plugin() {
        name=$1
        git_user=$2
        if [ ! -d ~/.pyenv/plugins/${name} ]; then
            echo "installing ${name}..."
            git clone https://github.com/${git_user}/${name} ~/.pyenv/plugins/${name}
        else
            echo "    ${name} installed, skip"
        fi
    }

    pyenv_plugin pyenv-virtualenv AbaoFromCUG
    pyenv_plugin pyenv-doctor pyenv
    pyenv_plugin pyenv-update pyenv
    pyenv_plugin pyenv-pyright alefpereira
}

setup_asdf() {
    if [ ! -d ~/.asdf ]; then
        echo "installing asdf..."
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf
        . "$HOME/.asdf/asdf.sh"
    else
        echo "asdf installed, skip"
    fi

    asdf_plugin() {
        name=$1
        repository=$2
        if [ ! -d ~/.asdf/plugins/${name} ]; then
            echo "installing ${name}..."
            asdf plugin-add $name https://github.com/${repository}
        else
            echo "    ${name} installed, skip"
        fi
    }
    asdf_plugin bun cometkim/asdf-bun
    asdf_plugin rust code-lever/asdf-rust
    asdf_plugin nodejs asdf-vm/asdf-nodejs
}

setup_tmux() {
    if [ ! -d ~/.tmux ] || [ ! -f ~/.tmux.conf ]; then
        echo "installing oh-my-tmux..."
        if [[ -f ~/.tmux.conf ]]; then
            echo -e "\033[31m backup current .tmux.conf to ~/.tmux.conf.bak \033[0m"
            mv ~/.tmux.conf /tmp/tmux.conf.bak
        fi
        rm -rf ~/.tmux.conf
        git clone https://github.com/gpakosz/.tmux.git ~/.tmux
        ln -s -f ~/.tmux/.tmux.conf ~/.tmux.conf
    else
        echo "oh-my-tmux installed, skip"
    fi
}

setup_fzf() {
    if [ ! -f ~/.fzf/install ]; then
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
        ~/.fzf/install --bin
    fi
}

setup_yazi() {
    yazi_plugin() {
        name=$1
        repository=$2
        if [ ! -d ~/.config/yazi/plugins/${name} ]; then
            echo "installing ${name}..."
            git clone https://github.com/$repository ~/.config/yazi/plugins/$name

        else
            echo "    ${name} installed, skip"
        fi
    }
    yazi_plugin keyjump.yazi DreamMaoMao/keyjump.yazi

}

# --------------choice--------------------

install_terminal() {
    setup_tmux
    setup_fzf
    setup_yazi
    yay_packages+=(
        tmux
        lazygit
        zsh
        openssh
        neovim
    )
}

install_env() {
    setup_pyenv
    setup_asdf
}

install_develop() {
    yay_packages+=(
        pkgfile
        man-db
        cmake
        git
        ninja
        eigen
        go
    )
    apt_packages+=(
        cmake
        git
    )
}

install_desktop() {
    yay_packages+=(
        base base-devel linux linux-firmware yay
        hyprland hyprpaper hyprpicker hypridle hyprlock
        xdg-desktop-portal-hyprland polkit-gnome
        libinput-gestures
        wl-clipboard
        brightnessctl

        sof-firmware libva-intel-driver libva-mesa-driver
        tlp
        networkmanager
        pipewire pipewire-pulse pipewire-jack pipewire-audio
        bluez-utils blueman
        mpd mpd-mpris playerctl pavucontrol
    )
    yay_packages+=(
        whitesur-gtk-theme whitesur-cursor-theme-git whitesur-icon-theme
        wofi waybar aylurs-gtk-shell
        nwg-bar nwg-displays nwg-look
        conky
    )

    # input method & fonts
    yay_packages+=(
        fcitx5 fcitx5-configtool fcitx5-pinyin-zhwiki fcitx5-chinese-addons
        fcitx5-gtk fcitx5-qt fcitx5-breeze

        ttf-hack-nerd ttf-cascadia-code-nerd ttf-firacode-nerd
        adobe-source-han-serif-cn-fonts adobe-source-han-sans-cn-fonts
        noto-fonts-emoji
        ttf-humor-sans
    )
    # basic tools
    yay_packages+=(
        cups
        imagemagick
        ksnip gimp grimblast-git
    )
    # apps
    yay_packages+=(
        wps-office
        clash-for-windows-bin
        firefox
        linuxqq-nt-bwrap wechat-universal-bwrap
        telegram-desktop feishu-bin
        krita
        vlc obs-studio
        ario
        unarchiver
        pot-translation
        code
        wezterm kitty alacritty
    )
    # others
    yay_packages+=(
        fastfetch
        rsync
        lsof
    )

    download ~/Pictures/wallpapers/nature-3058859.jpg https://gitlab.manjaro.org/artwork/wallpapers/wallpapers-2018/-/raw/master/nature-3058859.jpg
    download ~/Pictures/wallpapers/nature-3181144.jpg https://gitlab.manjaro.org/artwork/wallpapers/wallpapers-2018/-/raw/master/nature-3181144.jpg
    additional_commands+=(
        "hyprpm update"
        "hyprpm add https://github.com/hyprwm/hyprland-plugins"
        "hyprpm add https://github.com/levnikmyskin/hyprland-virtual-desktops"
        "hyprpm add https://github.com/KZDKM/Hyprspace.git"
        "hyprpm enable virtual-desktops"

        "systemctl enable bluetooth"
        "systemctl enable --user pipewire"
        "systemctl enable --user pipewire-pulse"
        "sudo usermode -aG audio $USER"
        "sudo usermode -aG video $USER"
        "sudo usermode -aG lp $USER"

    )
}

install_texlive() {
    yay_packages+=(
        sioyek
        texlive-latex
        texlive-xetex
        texlive-binextra
        texlive-latexrecommended
        texlive-latexextra
        texlive-fontsrecommended
        texlive-fontsextra
        texlive-bibtexextra
        texlive-mathscience

        texlive-langcjk
        texlive-langchinese

        texlive-plaingeneric
    )
}

if [[ $args_only = terminal ]]; then
    install_terminal
elif [[ $args_only = env ]]; then
    install_env
elif [[ $args_only = texlive ]]; then
    install_texlive
elif [[ $args_only = develop ]]; then
    install_env
    install_terminal
    install_develop
elif [[ $args_only = full ]]; then
    install_terminal
    install_env
    install_develop
    install_desktop
    install_texlive
fi

if [ -n "${yay_packages}" ] && command -v yay >/dev/null 2>&1; then
    installed_packages="$(yay -Qq | sort)"
    yay_packages=$(printf "%s\n" ${yay_packages[*]} | sort)
    missed_packages=$(comm -23 <(echo "$yay_packages") <(echo "$installed_packages"))
    echo $missed_package
    if [[ -n "$missed_packages" ]]; then
        echo "these packages are required but not installed:"
        echo "   yay -S $(echo $missed_packages)"
    fi
    explicit_packages="$(yay -Qettq | sort)"
    missed_packages=$(comm -23 <(echo "$explicit_packages") <(echo "$yay_packages"))
    if [[ -n "$missed_packages" ]]; then
        echo "these packages are explicitly installed but not required"
        echo "   yay -S $(echo $missed_packages)"
    fi
elif [ -n "${apt_packages}" ] && command -v apt >/dev/null 2>&1; then
    echo "please install manually:"
    echo "   sudo apt install ${apt_packages[@]}"
else
    echo "\033[31m Don't support current system \033[0m"
fi

if [[ -n "${additional_commands[@]}" ]]; then
    echo "please install manually:"
    for command in "${additional_commands[@]}"; do
        echo "    $command"
    done
fi
