#!/usr/bin/env bash

set -e

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

config=$1
case $config in
shell)
	CONFIG="shell.conf.yaml"
	;;
full)
	CONFIG="full.conf.yaml"
	;;
*)
	echo "First argument must be shell or full"
	exit 1
	;;
esac

args=("${@}")

unset args[0]

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${args[@]}"
