#!/usr/bin/env bash
echo "update package info"

groups=(base-devel xorg)

group_pkgs=()
for group in "${groups[@]}"
do
    for package in $(yay -Sg "${group}" | awk '{print $2}')
    do
        group_pkgs[${#group_pkgs[*]}]=$package
    done
done

installed_packages=$(yay -Q)

function is_in_group() {
    pkg_name=$1
    if [[ "${group_pkgs[*]}" =~ $pkg_name ]];then
        return 1
    fi
    return 0
}

function is_installed() {
    pkg_name=$1
    if [[ "${installed_packages[*]}" =~ $pkg_name ]]; then
        return 1
    fi
    return 0
}

required_packages=($(cat yay.lock|xargs))
packages=()

for package in "${required_packages[@]}"
do
    is_in_group "$package"
    if [ $? == 0 ]; then
       is_installed "$package"
       if [ $? == 0 ]; then
            echo "check package $package"
            packages[${#packages[@]}]=$package
       fi
    fi
done

cpu_vendor=$(lscpu|grep Vendor|awk '{print $3}')
if [ "$cpu_vendor" == "AuthenticAMD" ]; then
    cpu_microcode="amd-ucode"
else
    cpu_microcode="intel-ucode"
fi

packages[${#packages[*]}]=$cpu_microcode

echo  "${packages[*]}"
yay -S --needed "${packages[@]}"

