#!/usr/bin/env sh

echo "save package info to yay.lock"

groups=(base-devel xorg)
group_pkgs=()
for group in ${groups[*]}
do
    for package in $(yay -Sg ${group}|awk '{print $2}')
    do
        group_pkgs[${#group_pkgs[*]}]=$package
    done
done

function is_black() {
    pkg_name=$1
    if [[ "${group_pkgs[*]}" =~ "$pkg_name" ]];then
        return 1
    fi
    return 0
}

rm -rf yay.lock

for package in $(yay -Qetq)
do
    is_black $package
    if [ $? == 0 ];then
        echo $package >> yay.lock
    fi
done

