export TERMINAL=alacritty

if [[ $(uname) == Linux ]]; then

	if (( $+commands[uwsm] )); then
		if uwsm check may-start -q && uwsm select; then
			[ -f "$HOME/.config/user-dirs.dirs" ] && . "$HOME/.config/user-dirs.dirs"
			exec uwsm start default
		fi
	fi
fi
