export TERMINAL=alacritty

if uname | grep -qi linux; then
	export QT_IM_MODULE=fcitx
	export XMODIFIERS="@im=fcitx"
	export SDL_IM_MODULE=fcitx
	export GLFW_IM_MODULE=ibus
	export INPUT_METHOD=fcitx
	export QT_AUTO_SCREEN_SCALE_FACTOR=1
	export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
	export QT_QPA_PLATFORMTHEME=qt5ct
else
fi
