
# version manager
if [[ -d $HOME/.pyenv ]]; then
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

if [[ -d $HOME/.asdf ]]; then
    . "$HOME/.asdf/asdf.sh"
    export NVM_NODEJS_ORG_MIRROR=https://mirrors.ustc.edu.cn/node/
fi

# environment variable

export PATH="$PATH:$HOME/.local/bin"

if command -v go >/dev/null 2>&1; then
	export PATH="$PATH:$(go env GOBIN):$(go env GOPATH)/bin"
	export GOPROXY=https://goproxy.cn
fi

export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

if [ -e "$HOME/.cargo/env" ]; then
    . "$HOME/.cargo/env"
fi

export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/.local/go/bin
export PATH=$PATH:/opt/pot

export WECHAT_DATA_DIR=$HOME/Documents/wechat
export NLTK_DATA=$HOME/Documents/nltk_data


export EDITOR=nvim

