# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk

### Start of programs
GLIBC_VER=$(ldd --version | head -n 1 | awk '{print $NF}')

zinit light-mode for zdharma-continuum/zinit-annex-bin-gem-node
zinit light zdharma-continuum/zinit-annex-binary-symlink

### End of programs

### Start of plugins
zi for \
 OMZL::key-bindings.zsh \
 OMZL::history.zsh

zi wait lucid for \
 OMZL::clipboard.zsh \
 OMZL::completion.zsh \
 OMZL::git.zsh \
 OMZL::grep.zsh \
 OMZP::zoxide \

zi wait"2" lucid for \
 OMZP::python \
 OMZP::pip \
 OMZP::kubectl \
 OMZP::docker \
 OMZP::eza \
 OMZP::command-not-found \
 OMZP::bun \
 OMZP::git \
 OMZP::mise \
 OMZP::uv \
 OMZP::docker


zi depth"1" for \
  jeffreytse/zsh-vi-mode \
  romkatv/powerlevel10k \
  zsh-users/zsh-syntax-highlighting \
  zsh-users/zsh-autosuggestions

zi for \
    atload"zicompinit; zicdreplay" \
    blockf \
    lucid \
    wait \
  zsh-users/zsh-completions


# For postponing loading `fzf`
zi wait"2" lucid for \
    OMZP::fzf

### End of plugins

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.config/shell/p10k.mise.zsh ]] || source ~/.config/shell/p10k.mise.zsh
[[ ! -f ~/.config/shell/p10k.zsh ]] || source ~/.config/shell/p10k.zsh



### Additional config

if (( $+commands[yay] )); then
     # avoid install python package to pyenv python site
     alias yay="ASDF_RUST_VERSION=system  ASDF_NODEJS_VERSION=system PYENV_VERSION=system /usr/bin/yay"
fi

if (( $+commands[apt] )); then
     # avoid install python package to pyenv python site
     alias apt="ASDF_RUST_VERSION=system  ASDF_NODEJS_VERSION=system PYENV_VERSION=system /usr/bin/apt"
fi

function passwordgen() {
    echo $(LC_ALL=C tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13; echo)
}

function sshr() {
    eval $(fzf --zsh)
    host=$(__fzf_list_hosts|fzf)
    ssh -t $host zsh --login -c "tmux attach || tmux new -s work"
}


# alias pip="uv pip"
alias vim=nvim
alias ocat="$(which cat)"

alias cat="$(which bat)"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

export FZF_COMPLETION_TRIGGER=','


### Local config
[[ ! -f ~/.zshrc.local ]] || source ~/.zshrc.local

