#!/usr/bin/env bash

wallpaper="$HOME/Pictures/wallpapers/nature-3181144.jpg"

screen_resolution=$(xdpyinfo | grep dimensions | cut -d' ' -f7)

convert "$wallpaper" -resize "$screen_resolution^" -gravity Center -extent "$screen_resolution" RGB:- | i3lock -n --raw "${screen_resolution}:rgb" -f --image /dev/stdin
