#!/usr/bin/env bash

# Terminate already running ags instances
killall -q ags
sleep 1
# Wait until the processes have been shut down
while pgrep -u $UID -x ags >/dev/null; do sleep 1; done

# Launch example
echo "---" | tee -a /tmp/ags.log
ags 2>&1 | tee -a /tmp/ags.log &
disown

echo "ags launched..."
