#!/usr/bin/env bash

# Terminate already running quickshell instances
killall -q quickshell
sleep 1
# Wait until the processes have been shut down
while pgrep -u $UID -x quickshell >/dev/null; do sleep 1; done

# Launch example
echo "---" | tee -a /tmp/quickshell.log
quickshell 2>&1 | tee -a /tmp/quickshell.log &

echo "quickshell launched..."
