#!/usr/bin/env bash

# Terminate already running bar instances
killall -q waybar
sleep 1 
# Wait until the processes have been shut down
while pgrep -u $UID -x waybar >/dev/null; do sleep 1; done

# Launch example
echo "---" | tee -a /tmp/waybar_example.log
waybar 2>&1 | tee -a /tmp/waybar_example.log & disown

echo "Bars launched..."
