[env]

RUSTUP_DIST_SERVER = "https://mirrors.ustc.edu.cn/rust-static"
RUSTUP_UPDATE_ROOT = "https://mirrors.ustc.edu.cn/rust-static/rustup"


[settings]
idiomatic_version_file_enable_tools = []
experimental = true
lockfile = true
node.gpg_verify = false


node.mirror_url="https://mirrors.aliyun.com/nodejs-release/"
npm.package_manager = "bun"

[tools]
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:artempyanykh/marksman" = "latest"
"aqua:mrjosh/helm-ls" = "latest"
"cargo:texlab" = "latest"
"npm:@delance/runtime" = {version="prerelease", bun_args= "--trust"}
"npm:@github/copilot-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:@vue/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:pyright" = "latest"
"npm:typescript" = "latest"
"npm:vim-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:debugpy" = "latest"
"pipx:zuban" = "latest"
bun = "latest"
clang-format = "latest"
fd = "latest"
lazygit = "latest"
node = "lts"
opencode = "latest"
ruff = "latest"
rust = "stable"
shfmt = "latest"
taplo = "latest"
tinymist = "latest"
tree-sitter = "latest"
typstyle = "latest"
usage = "latest"
uv = "latest"
yamlfmt = "latest"
yazi = "latest"
pnpm = "latest"
zoxide = "latest"
just = "latest"
jq = "latest"
bat = "latest"
eza = "latest"
codex = "latest"
fzf = "latest"
"github-cli" = "latest"
"github:JohnnyMorganz/luau-lsp" = "latest"
"github:colbymchenry/codegraph" = "latest"
"npm:@builder.io/ai-shell" = "latest"
